### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by explosivePython** [PrimeKidMN/Tampermonkey-Blooket-Hacks#1]
I put it into tampermonkey and it wont actuvate when I join a game

**Comment by PrimeKidMN** [comment]
Try making sure it is enabled through tampermonkey and then refresh when going into blooket. If this does not work upload a picture of the code and I will help you more.

**Comment by FloppaShploop** [comment]
Womp womp

**Comment by FloppaShploop** [comment]
If you want working hacks go to GitHub.io/05konz

**Comment by PrimeKidMN** [comment]
Number one, this is a conversation me and the guy trying to get these to work. Number two, please do not advertise other scripts on my repository especially stolen scripts like konz. Number three, I am trying to help this person please do not talk about anything different then fixing the issues. Floppa. if you persist I will seek to block you from this repository.

Thanks,
PrimeKidMN

1/29/2024

**Comment by ZamzamWate** [comment]
does this anti ban work

**Comment by PrimeKidMN** [comment]
Dear,
@ZamzamWate

So yes and no. Allow me to elaborate, the Anti-Ban script does work except the thing is it is not 100% safe and it only helps keeping you from getting banned. But it definitely is a must if you are hacking and you have absolutely no protection whatsoever. 
If you want more protection definitely pair this with a vpn or proxy. But there is no 100% safe way of hacking. From my testing I got banned after two times hacking without protection and 7 times with. I hope this helps! Also note that if you get banned using these hacks I am not responsible for your account. Please take this into account when you do anything that breaks the rules of any site. Don't blame others and be responsible.

Thanks,
@PrimeKidMN

**Comment by PrimeKidMN** [comment]
Also if you have an issue open a new one because this one is being closed.
